{% set version = "1.62.2" %}

# bazel 7+ requires setting up a toolchain so that the macOS SDK in a non-standard
# location is accepted, which would require bazel-toolchain etc.
{% set bz_version = "6.5.0" %}
{% set bz_base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: grpc_java_plugin
  version: {{ version }}

source:
  - url: https://github.com/grpc/grpc-java/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 30cfc954c2174493822601a74b876837986c444d9b9e917082994b5e34348f34
    patches:
      - patches/0001-Build-against-system-libprotobuf.patch
      - patches/0002-use-C-17.patch
      - patches/0003-Add-abseil-libs-for-newer-protobuf-versions.patch
      # backport https://github.com/grpc/grpc-java/commit/f299ef5e5832898fa29ede31dee1a6085b90c051
      # from compatibility with absl::string_view being equal to std::string_view
      - patches/0004-compiler-Prepare-for-C-protobuf-using-string_view.patch

  - fn: bazel
    url: {{ bz_base_url }}/{{ bz_version }}/bazel_nojdk-{{ bz_version }}-linux-x86_64  # [build_platform == "linux-64"]
    sha256: 218ce0aed544d29084f4d9ff98f01bc784b90fe4c79dab63fa990dc68e66eaa9           # [build_platform == "linux-64"]
    url: {{ bz_base_url }}/{{ bz_version }}/bazel_nojdk-{{ bz_version }}-linux-arm64   # [build_platform == "linux-aarch64"]
    sha256: 9b891320bb08beb54859870e371ac6749f14691ce06920ad32d696f0a6498811           # [build_platform == "linux-aarch64"]
    url: {{ bz_base_url }}/{{ bz_version }}/bazel_nojdk-{{ bz_version }}-darwin-arm64  # [build_platform == "osx-arm64"]
    sha256: 37017223885da29d8c42be781e8c11b84e71a3d9355b073d43b08a5dfa99229a           # [build_platform == "osx-arm64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - openjdk
    - openjdk 21  # [linux]
    - bazel-toolchain
    - libprotobuf
    - sed  # [osx]
  host:
    - libabseil {{ libabseil }}
    - libprotobuf {{ libprotobuf }}

test:
  commands:
    - test -f $PREFIX/bin/grpc_java_plugin

about:
  home: https://github.com/grpc/grpc-java/tree/master/compiler
  dev_url: https://github.com/grpc/grpc-java/tree/master/compiler
  doc_url: https://github.com/grpc/grpc-java/tree/master/compiler
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: gRPC Java Codegen Plugin for Protobuf Compiler
  description: |
    This generates the Java interfaces out of the service definition from a .proto file. It works with the Protobuf
    Compiler (protoc).

extra:
  skip-lints:
    - missing_hash
    - missing_source
  recipe-maintainers:
    - xhochy
    - conda-forge/bazel
    - conda-forge/grpc-cpp
