{% set name = "grpc_java_plugin" %}
{% set version = "1.38.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grpc/grpc-java/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 80119952caa2111abd708e350be01e0615d1510a862cf0151eeae573445f98fa
  patches:
    - 0001-Build-against-system-libprotobuf.patch

build:
  number: 0
  skip: true  # [not osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel
    - libprotobuf
  host:
    - libprotobuf

test:
  commands:
    - test -f $PREFIX/bin/grpc_java_plugin

about:
  home: https://github.com/grpc/grpc-java/tree/master/compiler
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: gRPC Java Codegen Plugin for Protobuf Compiler

extra:
  recipe-maintainers:
    - xhochy
